version: '2.0'
services:
  mongodb_container:
    image:  mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=medio_local
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: